name: platform_maps_flutter
description: A Flutter package that combines google_maps and apple_maps to provide a crossplatform native map implementation.
version: 2.1.0
homepage: https://github.com/LuisThein
repository: https://github.com/LuisThein/platform_maps_flutter
issue_tracker: https://github.com/LuisThein/platform_maps_flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.3.1
  google_maps_flutter_platform_interface: ^2.2.7
  apple_maps_flutter:
    git:
      url: https://github.com/mikeKane/apple_maps_flutter.git
      tag: v2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
